version: '3.8'

services:
  php-fpm:
    build:
      context: docker/php-fpm
    tty: true
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./storage/app/public/:/var/www/public/storage/
    tty: true
    ports:
      - "8999:80"
    networks:
      - laravel
    depends_on:
      - php-fpm

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./docker/postgres/datadir:/var/lib/postgresql/data
    ports:
      - "8101:5432"
    networks:
      - laravel

networks:
  laravel:
